name: exam_prep_app
description: Chapter-wise PYQ practice app for JEE & NEET aspirants.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.0

  # Fonts
  google_fonts: ^6.2.1

  # SVG support (future use)
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true